name: carsales
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.6
  - pip
  # BASICS
  - numpy
  - pandas
  - pip:
     - -e .  # install git checkout of carsales in editable mode

  # DEVELOPMENT ONLY PACKAGES (could also be kept in a separate environment file)
  - jupyterlab
  - pytest
  - pytest-cov
  - tox
  - pre_commit
  - nbdime
  - nbstripout
  - sphinx
  - recommonmark
  - pylint
  - black
